### ISSUE TITLE
Initial set up is getting stuck at 12%

### ISSUE THREAD

**Issue by Disorganise** [techandme/wordpress-vm#47]
Hi,
Have downloaded the wordpress ova and have tried to run it twice from scratch.  After logging in and changing timezones etc, the scripts go do their thing.

Eventually, it gets to the point where it is preparing to unpack mariadb-server and seems to get stuck.  (screenshot hopefully below)
![image](https://user-images.githubusercontent.com/18409322/56012706-0a5a9500-5d31-11e9-9a6c-1a4d121bac24.png)

resetting the VM and trying again generates a bunch of errors with duplicate entries, so I deleted the VM and re-imported the ova.  Different mirrors offered and accepted, but same eventual result.

not sure if there's anything I can do to kick it along?

**Comment by enoch85** [comment]
I will test this later this weekend.

**Comment by enoch85** [comment]
@Disorganise Please try this on VMware Player instead to see if that might be the case,

Thanks!

**Comment by Disorganise** [comment]
Hi,  I downloaded vmware and confirm the set-up does complete.  So seems a problem with virtual box?

**Comment by Disorganise** [comment]
Something else I noticed with virtual box versus vmware.  at the very start, there is some complaint about command not found.  on vmware, I seem to recall seeing some coloured writing...network ok or something iirc
![image](https://user-images.githubusercontent.com/18409322/56075718-43b30380-5e0a-11e9-9cd6-efc6954d8e46.png)

**Comment by Disorganise** [comment]
Some further experimenting....
If you reset the VM after the above 'command not found' errors so that the VM reboots and starts over, then instead of getting 'command not found', you get the coloured writing that network is found online.
Not only that, but the set-up completes all the way to the end without further issue.

If you do **not** reset the VM, then it gets stuck at the 12% - I also tried leaving the disk as vmdk instead of importing to vdi, but it makes no different.

**Comment by enoch85** [comment]
Hi!

Thanks for that. The `command not found` error is something that will be fixed in the next release, it's nothing serious, just cosmetic.

Also, you can't run the setup-script twice. If yo want to run the setup script again you need to delete the VM, and then re-import it.

**Comment by enoch85** [comment]
This issue is now solved: https://github.com/techandme/wordpress-vm/commit/40ac02404021a176f6db448970d2e77342a9d965

**Comment by Powerbless** [comment]
i think it is not solved when using virtualbox. i get the same error (first comment) but it stuck at 27%
