### ISSUE TITLE
Setup Script failed on WP config

### ISSUE THREAD

**Issue by Pookha** [techandme/wordpress-vm#92]
I just installed the Hyper V WP Vm tonight and hit a snag during the config of the Wordpress instance. I'm unsure what my next steps should be or if I should try to restart the setup script.

![Image](https://github.com/user-attachments/assets/6ed3a996-e845-4470-9fde-3e1ce12b643a)

**Comment by enoch85** [comment]
Can you please post the output of the journalctl command like it says in the error message?

**Comment by Pookha** [comment]
Yes, here is that output:

![Image](https://github.com/user-attachments/assets/84fbf6eb-0d0f-4623-bc19-c82a2108c718)

**Comment by enoch85** [comment]
Great, thanks! I see the error now.

Please start over, clearing everything you did by removing the VM, and deploy a fresh one. This time, don't choose adminer.

I will fix the real issue later today.

**Comment by enoch85** [comment]
It should now be fixed, please try to install adminer again. 👍

**Comment by Pookha** [comment]
I started from the original vm image again and the install script is still failing for me after I setup my Wordpress instance. I'm attaching the screenshot below. For this setup I did not install adminer even though I started after your fix. 

Should I by entering "y" for the prompt to delete all post from the default Wordpress install?

![Image](https://github.com/user-attachments/assets/19f1895a-0568-41a9-89ac-f657342726fc)

Also here is a pic of the server startup. nginx is not able to start from a fresh reboot

![Image](https://github.com/user-attachments/assets/1602bc09-846c-43bf-a537-8e7d90bc9b74)

**Comment by enoch85** [comment]
Hmm, so what's the output of `cat /var/log/nginx.log`

**Comment by Pookha** [comment]
it seems to me missing 

![Image](https://github.com/user-attachments/assets/c10adbb1-f19e-49b3-a5ba-c28d5dfcab1e)

I can always just start over again and simply attempt to install no apps, then return and install them one by one if you think that will help.

**Comment by enoch85** [comment]
Sorry, it should be /var/log/nginx/error.log.

You need to delete, import, and start over. You cannot run it twice.

**Comment by Jed3176** [comment]
Here is what the error is I just ran into it today. 
2025/05/01 15:49:08 [error] 1100#1100: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 716; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 727; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 730; PHP message: PHP Warning:  Undefined array key "scheme" in /var/www/html/wordpress/wp-includes/canonical.php on line 751; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 716; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 727; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 730; PHP message: PHP Warning:  Undefined array key "scheme" in /var/www/html/wordpress/wp-includes/canonical.php on line 751" while reading response header from upstream, client: 192.168.6.2, server: , request: "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0", upstream: "fastcgi://unix:/var/run/php8.3-fpm-wordpress.sock:"
2025/05/01 15:49:08 [error] 1100#1100: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 716; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 727; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 730; PHP message: PHP Warning:  Undefined array key "scheme" in /var/www/html/wordpress/wp-includes/canonical.php on line 751; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 716; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 727; PHP message: PHP Warning:  Undefined array key "host" in /var/www/html/wordpress/wp-includes/canonical.php on line 730; PHP message: PHP Warning:  Undefined array key "scheme" in /var/www/html/wordpress/wp-includes/canonical.php on line 751" while reading response header from upstream, client: 192.168.6.2, server: , request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php8.3-fpm-wordpress.sock:"
